rendering
style
	^'
body { 
	font-size: 10px;
	font-family: sans-serif;
	}
	
#menu li { 
	display: inline;
	padding-left: 10px;
	padding-right: 10px;
	border: 1px solid black 
	}

#list { width: 15% }
.key { width: 100px; }
#list ul:first-child { 
	height: 500px;
	max-height: 500px;
	min-height: 500px;
	overflow: scroll;
	}

.responses, .responses input { width: 100% }
.cities { display: none }
#content { vertical-align: top; width: 50% }
#content table { width: 100% }
'